### ISSUE TITLE
Support upgrading 1.12.2 worlds

### ISSUE THREAD

**Issue by PureGero** [PureGero/MultiPaper#115]
When upgrading from 1.12, an error is thrown when attempting to load chunks.

```[17:32:54 ERROR]: Could not apply datafixers for chunk task: Chunk task: class:com.destroystokyo.paper.io.chunk.ChunkLoadTask, for world 'world', (-22,19), hashcode:1470685016, priority: -1
java.lang.NullPointerException: Cannot invoke "net.minecraft.nbt.NBTTagCompound.p(String)" because the return value of "net.minecraft.world.level.storage.WorldPersistentData.a(String, int)" is null
      at net.minecraft.world.level.levelgen.structure.LegacyStructureDataHandler.populateCaches(LegacyStructureDataHandler.java:180) ~[?:?]
      at net.minecraft.world.level.levelgen.structure.LegacyStructureDataHandler.<init>(LegacyStructureDataHandler.java:53) ~[?:?]
      at net.minecraft.world.level.levelgen.structure.LegacyStructureDataHandler.getLegacyStructureHandler(LegacyStructureDataHandler.java:239) ~[?:?]
      at net.minecraft.world.level.chunk.storage.ChunkStorage.upgradeChunkTag(ChunkStorage.java:98) ~[?:?]
      at com.destroystokyo.paper.io.chunk.ChunkLoadTask.executeTask(ChunkLoadTask.java:94) ~[multipaper-1.18.1.jar:git-MultiPaper-"454602d"]
      at com.destroystokyo.paper.io.chunk.ChunkLoadTask.run(ChunkLoadTask.java:38) ~[multipaper-1.18.1.jar:git-MultiPaper-"454602d"]
      at com.destroystokyo.paper.io.QueueExecutorThread.pollTasks(QueueExecutorThread.java:118) ~[multipaper-1.18.1.jar:git-MultiPaper-"454602d"]
      at com.destroystokyo.paper.io.QueueExecutorThread.run(QueueExecutorThread.java:51) ~[multipaper-1.18.1.jar:git-MultiPaper-"454602d"]```

**Comment by PureGero** [comment]
An alternative solution is to upgrade your world with a program such as https://www.amuletmc.com/.
