### ISSUE TITLE
REGRESSION: multipaper 1.18.1 version 134 broke minecraft-stress-test bots

### ISSUE THREAD

**Issue by xymb-endcrystalme** [PureGero/MultiPaper#131]
The server bots are connecting to reports:
```[15:48:31 INFO]: Bot10 lost connection: Internal Exception: io.netty.handler.codec.DecoderException: java.io.IOException: Bad packet id 5```

The second server reports:
```
[15:48:31 FATAL]: Error executing task on Server
java.lang.NullPointerException: Cannot invoke "net.minecraft.server.level.EntityPlayer.M()" because "player" is null
        at puregero.multipaper.externalserverprotocol.AdvancementGrantProgressPacket.lambda$handle$0(AdvancementGrantProgressPacket.java:45) ~[multipaper-1.18.1.jar:git-MultiPaper-"9b38814"]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[multipaper-1.18.1.jar:git-MultiPaper-"9b38814"]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:150) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:23) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1424) ~[multipaper-1.18.1.jar:git-MultiPaper-"9b38814"]
        at net.minecraft.server.MinecraftServer.c(MinecraftServer.java:194) ~[multipaper-1.18.1.jar:git-MultiPaper-"9b38814"]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:122) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1402) ~[multipaper-1.18
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1395) ~[multipaper-1.18.1.jar:g
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:133) ~[?:?]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1373) ~[multipaper-1.1
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1279) ~[multipaper-1.18.1.jar:
        at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:325) ~[multipaper-1.18.1.j
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

Bots still work on version 133

**Comment by xymb-endcrystalme** [comment]
Actually, some bots join, but not all.
When trying with 10, one or two will succeed.

**Comment by PureGero** [comment]
This is an issue for https://github.com/PureGero/minecraft-stress-test.
But, try the latest commit first.
