### ISSUE TITLE
Server crash happens sometimes when two servers generate the world

### ISSUE THREAD

**Issue by xymb-endcrystalme** [PureGero/MultiPaper#134]
[crash_log.txt](https://github.com/PureGero/MultiPaper/files/8443124/crash_log.txt)

**This problem happens only when generating new chunks. It won't affect pregenerated worlds.**

When two servers are generating new chunks it sometimes results in a crash.
This happens without Spottedleaf's patch pretty rarely (I managed to reproduce it with 24 MultiPapers)...
However, with Spottedleaf's patches _and_ a plugin that changes view distances it happens pretty consistently.

**Steps to reproduce:**
- Compile [this repo](https://github.com/xymb-endcrystalme/awful_repo_please_ignore) and put the plugin into MP servers.
- `rm -R world` on Master
- Start Master
- Start two MP servers
- Put 20 bots on each of the server

It will crash within seconds. The only thing "awful_repo_please_ignore" does is it changes view distance randomly for every player every few seconds.

**Comment by xymb-endcrystalme** [comment]
The problem still persists in 1.18.2, but now results in a different message:
```
java.util.concurrent.CompletionException: java.lang.IllegalStateException: Staring interpolation twice
        at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315) ~[?:?]
        at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320) ~[?:?]
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1770) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.IllegalStateException: Staring interpolation twice
        at net.minecraft.world.level.levelgen.NoiseChunk.initializeForFirstCellX(NoiseChunk.java:297) ~[multipaper-1.18.2.jar:MultiPaper-1.18.2-13]
        at net.minecraft.world.level.levelgen.NoiseBasedChunkGenerator.doFill(NoiseBasedChunkGenerator.java:336) ~[?:?]
        at net.minecraft.world.level.levelgen.NoiseBasedChunkGenerator.lambda$fillFromNoise$12(NoiseBasedChunkGenerator.java:310) ~[?:?]
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?]
        ... 3 more 
```

Doesn't happen if you're running only one server or your chunks are pregenerated.
