### ISSUE TITLE
return value of "net.minecraft.server.players.PlayerList.a(java.util.UUID)" is null

### ISSUE THREAD

**Issue by zekepari** [PureGero/MultiPaper#139]
```
[20:58:58 FATAL]: Error executing task on Server
java.lang.NullPointerException: Cannot read field "d" because the return value of "net.minecraft.server.players.PlayerList.a(java.util.UUID)" is null
        at puregero.multipaper.externalserverprotocol.PlayerChangeGamemodePacket.lambda$handle$0(PlayerChangeGamemodePacket.java:35) ~[multipaper-1.18.1.jar:git-MultiPaper-142]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[multipaper-1.18.1.jar:git-MultiPaper-142]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:150) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:23) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1434) ~[multipaper-1.18.1.jar:git-MultiPaper-142]
        at net.minecraft.server.MinecraftServer.c(MinecraftServer.java:194) ~[multipaper-1.18.1.jar:git-MultiPaper-142]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:122) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1411) ~[multipaper-1.18.1.jar:git-MultiPaper-142]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1404) ~[multipaper-1.18.1.jar:git-MultiPaper-142]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:133) ~[?:?]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1382) ~[multipaper-1.18.1.jar:git-MultiPaper-142]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1288) ~[multipaper-1.18.1.jar:git-MultiPaper-142]
        at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:325) ~[multipaper-1.18.1.jar:git-MultiPaper-142]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

**Comment by PureGero** [comment]
This error can be safely ignored.
