### ISSUE TITLE
The player client's item bar will be locked in the first grid

### ISSUE THREAD

**Issue by dandanlong123** [PureGero/MultiPaper#148]
When the number of sub servers reaches two, the item bar will always be locked in the first grid, and the mouse wheel cannot be dragged to the later item bar to automatically bounce back to the first grid

**Comment by PureGero** [comment]
Can you send your master's logs?

**Comment by dandanlong123** [comment]
[Uploading 2022-04-21-4.log…]()

**Comment by dandanlong123** [comment]
_
[2022-04-21-4.log](https://github.com/PureGero/MultiPaper/files/8536907/2022-04-21-4.log)
_

**Comment by PureGero** [comment]
Can you also send the logs for the other server?

**Comment by dandanlong123** [comment]
Sorry, wait a minute. The file is too big

**Comment by dandanlong123** [comment]
https://pastebin.ubuntu.com/p/7vnZ3cgrZt/

**Comment by PureGero** [comment]
The timestamps of the two logs don't line up. One log was taken 10 minutes before the other

**Comment by dandanlong123** [comment]
These are the logs of two different sub servers, because the start-up time is different, because the first sub server starts the item bar normally. When the second sub server starts, the item bar is forced to be locked in the first grid

**Comment by PureGero** [comment]
Are you able to send the logs of the first sub server starting at 23:33:23?

**Comment by dandanlong123** [comment]
https://pastebin.ubuntu.com/p/mfw432F4PV/

**Comment by dandanlong123** [comment]
https://pastebin.ubuntu.com/p/mfw432F4PV/

**Comment by dandanlong123** [comment]
In this link is the time period of the first sub server

**Comment by dandanlong123** [comment]
[23:33:21] [Server thread/WARN]: 	at FluffyMachines-Build 16 zh-CN(ybw0014) (git 1d507d1).jar//io.ncbpfluffybear.fluffymachines.items.Barrel$3.tick(Barrel.java:313)
[23:33:21] [Server thread/WARN]: 	at SlimefunOptimized-v1.2.3_货运极致优化.jar//io.github.thebusybiscuit.slimefun4.implementation.tasks.TickerTask.tickBlock(TickerTask.java:189)
[23:33:21] [Server thread/WARN]: 	at SlimefunOptimized-v1.2.3_货运极致优化.jar//io.github.thebusybiscuit.slimefun4.implementation.tasks.TickerTask.lambda$tickLocation$2(TickerTask.java:170)
[23:33:21] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftTask.run(CraftTask.java:101)
[23:33:21] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483)
[23:33:21] [Server thread/WARN]: java.lang.IllegalArgumentException: java.lang.ClassCastException@66c55682
[23:33:21] [Server thread/WARN]: 	at SlimefunOptimized-v1.2.3_货运极致优化.jar//io.github.thebusybiscuit.slimefun4.libraries.dough.items.nms.ItemNameAdapter18.getName(ItemNameAdapter18.java:32)
[23:33:21] [Server thread/WARN]: 	at SlimefunOptimized-v1.2.3_货运极致优化.jar//io.github.thebusybiscuit.slimefun4.libraries.dough.items.ItemUtils.getItemName(ItemUtils.java:51)
[23:33:21] [Server thread/WARN]: 	at FluffyMachines-Build 16 zh-CN(ybw0014) (git 1d507d1).jar//io.ncbpfluffybear.fluffymachines.items.Barrel.updateMenu(Barrel.java:451)
[23:33:21] [Server thread/WARN]: 	at FluffyMachines-Build 16 zh-CN(ybw0014) (git 1d507d1).jar//io.ncbpfluffybear.fluffymachines.items.Barrel.storeItem(Barrel.java:411)
[23:33:21] [Server thread/WARN]: 	at FluffyMachines-Build 16 zh-CN(ybw0014) (git 1d507d1).jar//io.ncbpfluffybear.fluffymachines.items.Barrel.tick(Barrel.java:341)
[23:33:21] [Server thread/WARN]: 	at FluffyMachines-Build 16 zh-CN(ybw0014) (git 1d507d1).jar//io.ncbpfluffybear.fluffymachines.items.Barrel$3.tick(Barrel.java:313)
[23:33:21] [Server thread/WARN]: 	at SlimefunOptimized-v1.2.3_货运极致优化.jar//io.github.thebusybiscuit.slimefun4.implementation.tasks.TickerTask.tickBlock(TickerTask.java:189)
[23:33:21] [Server thread/WARN]: 	at SlimefunOptimized-v1.2.3_货运极致优化.jar//io.github.thebusybiscuit.slimefun4.implementation.tasks.TickerTask.lambda$tickLocation$2(TickerTask.java:170)
[23:33:21] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftTask.run(CraftTask.java:101)

**Comment by dandanlong123** [comment]
Since 33 minutes, these useless errors have been reported because the plug-ins are not compatible with the core

**Comment by dandanlong123** [comment]
Another problem is that when players go back and forth into two servers, it is easy to cause the server to crash

**Comment by dandanlong123** [comment]
Can this problem be solved？

**Comment by xymb-endcrystalme** [comment]
> Another problem is that when players go back and forth into two servers, it is easy to cause the server to crash

Can you make a new issue and describe how exactly to reproduce it?

**Comment by dandanlong123** [comment]
Let's solve the problem of item list first

**Comment by PureGero** [comment]
Are both servers using a different name? If they both have the same name `server01172`, then it will cause issues like the one you are seeing.

**Comment by dandanlong123** [comment]
![Uploading F$BNP523$3[(%VFRAR8EAS3(1).png…]()

**Comment by dandanlong123** [comment]
> 两个服务器是否使用不同的名称？如果它们都具有相同的 name `server01172`，那么它将导致您所看到的问题。

![Uploading F$BNP523$3[(%VFRAR8EAS3(1).png…]()

**Comment by dandanlong123** [comment]
After testing, it's not this problem. I've changed the name, but each time I turn on the server, the names of the two servers will change automatically and randomly, but at least the name is not the same. The test results will still cause the item column to lock in the first grid

**Comment by dandanlong123** [comment]
![Uploading F$BNP523$3[(%VFRAR8EAS3(1).png…]()

**Comment by dandanlong123** [comment]
> 两个服务器是否使用不同的名称？如果它们都具有相同的 name `server01172`，那么它将导致您所看到的问题。

**Comment by xymb-endcrystalme** [comment]
> the names of the two servers will change automatically and randomly

That shouldn't happen. You have something seriously wrong with your configuration.
How are you running your server exactly? Try just three terminals on the same machine, no Dockers, no Pterodactyls.

**Comment by dandanlong123** [comment]
I'm running on the same machine. I don't need anything else. It's completely local

**Comment by PureGero** [comment]
Create a new issue if this still occurs after the 1.19 version is released.
