### ISSUE TITLE
java.lang.NoSuchMethodError: 'float java.util.Random.nextFloat(float)'

### ISSUE THREAD

**Issue by RemcoSpigot** [PureGero/MultiPaper#185]
# Improvement
Whenever a player joins and the chunk itself has a vine. Upon the tick that the vine grows, the server crashes.
This happens on older JDK 17 (specifically EA) versions soly. 

Issue was found due to testing on older OpenJDK EA version. Docker images for Alpine are no longer updated by the OpenJDK team.

JAR is obtained from the multipaper.io website.

## Technical details
**Version**: MultiPaper-1.18.2-65
**OS**: Alpine 3.14 (the reason why it shows)
**JDK**: OpenJDK 17-ea+14

**Error**:
```java
net.minecraft.ReportedException: Exception ticking world
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1627) ~[multipaper-1.18.2.jar:MultiPaper-1.18.2-65]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:492) ~[multipaper-1.18.2.jar:MultiPaper-1.18.2-65]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1466) ~[multipaper-1.18.2.jar:MultiPaper-1.18.2-65]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1236) ~[multipaper-1.18.2.jar:MultiPaper-1.18.2-65]
        at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:323) ~[multipaper-1.18.2.jar:MultiPaper-1.18.2-65]
        at java.lang.Thread.run(Thread.java:831) ~[?:?]
Caused by: java.lang.NoSuchMethodError: 'float java.util.Random.nextFloat(float)'
        at net.minecraft.world.level.block.CaveVinesBlock.getGrowIntoState(CaveVinesBlock.java:56) ~[multipaper-1.18.2.jar:MultiPaper-1.18.2-65]
        at net.minecraft.world.level.block.GrowingPlantHeadBlock.randomTick(GrowingPlantHeadBlock.java:61) ~[?:?]
        at net.minecraft.world.level.block.state.BlockBehaviour$BlockStateBase.randomTick(BlockBehaviour.java:1015) ~[?:?]
        at net.minecraft.server.level.ServerLevel.tickChunk(ServerLevel.java:867) ~[?:?]     
        at net.minecraft.server.level.ServerChunkCache.tickChunks(ServerChunkCache.java:1060) ~[?:?]
        at net.minecraft.server.level.ServerChunkCache.tick(ServerChunkCache.java:914) ~[?:?]
        at net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:640) ~[?:?]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1608) ~[multipaper-1.18.2.jar:MultiPaper-1.18.2-65]
        ... 5 more
        at java.lang.Thread.run(Thread.java:831) ~[?:?]
```

This is related to https://github.com/PaperMC/Paper/issues/7062

## Proposal
Add in the README release specific JDK versions and possibly a Docker section showing the supported images. 

This to ensure that operators don't run outdated Java versions on accident since it's common practice for Oracle to include EA into GA images.

**Comment by PureGero** [comment]
This is an issue with the upstream, and I see no point in MultiPaper trying to solve this issue. Early access Java builds are not supported.

To fix this crash: Update your version of Java to the latest version 17 build.
