### ISSUE TITLE
I need some help

### ISSUE THREAD

**Issue by CivicXFB** [PureGero/MultiPaper#8]
I can't find the World/level.dat thing when I'm using it. But my subserver doesn't load the map at all and I don't know how he syncs it. I can't find those sync buttons either, I just want to know how it works! Thank you, for reading my message out of your busy schedule!

**Comment by CivicXFB** [comment]
[19:52:36 ERROR]: java.nio.file.NoSuchFileException: world\level.dat
[19:52:36 ERROR]:       at java.base/sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:85)
[19:52:36 ERROR]:       at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:103)
[19:52:36 ERROR]:       at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:108)
[19:52:36 ERROR]:       at java.base/sun.nio.fs.WindowsFileSystemProvider.newByteChannel(WindowsFileSystemProvider.java:236)
[19:52:36 ERROR]:       at java.base/java.nio.file.Files.newByteChannel(Files.java:375)
[19:52:36 ERROR]:       at java.base/java.nio.file.Files.newByteChannel(Files.java:426)
[19:52:36 ERROR]:       at java.base/java.nio.file.Files.readAllBytes(Files.java:3272)
[19:52:36 ERROR]:       at puregero.multipaper.server.handlers.ReadLevelHandler.lambda$handle$0(ReadLevelHandler.java:19)
[19:52:36 ERROR]:       at puregero.multipaper.server.Worker.run(Worker.java:37)

**Comment by PureGero** [comment]
Hi, I've fixed this error message in the latest version v1.17.1-300, thank you for reporting it.

As for how it syncs: the worlds are no longer stored on the subserver, but instead on the MultiPaper-Master. The MultiPaper-Master automatically distributes the world to the subservers, no buttons needed. If you run the latest version, it will generate a new world for you instead of throwing that error, so you can use that to locate where the synced world is stored within MultiPaper-Master.

**Comment by CivicXFB** [comment]
Thank you for your help!

**Comment by CivicXFB** [comment]
My MultiPaper-Master is running on Bc but it doesn't work the way you describe he only generates the MultiPaperProxy port but doesn't actually set it up my idea is that there should be a Mysql datastore fill address or a local fill address. I don't know if this problem is my own! Because when I was using the new version it appeared that the ban-player.json file was not found and the folder I created was not valid!

**Comment by CivicXFB** [comment]
My MultiPaper-Master is running on Bc but it doesn't work the way you describe he only generates the MultiPaperProxy port but doesn't actually set it up my idea is that there should be a Mysql datastore fill address or a local fill address. I don't know if this problem is my own! Because when I was using the new version it appeared that the ban-player.json file was not found and the folder I created was not valid!

Translated with www.DeepL.com/Translator (free version)

**Comment by CivicXFB** [comment]
My MultiPaper-Master is running on Bc but it doesn't work the way you describe he only generates the MultiPaperProxy port but doesn't actually set it up my idea is that there should be a Mysql datastore fill address or a local fill address. I don't know if this problem is my own! Because when I was using the new version it appeared that the ban-player.json file was not found and the folder I created was not valid!

**Comment by PureGero** [comment]
Hi, I've fixed the error message about the ban-player.json file in the latest version v1.17.1-308, thank you for reporting it.

Hopefully that also solves your other issue

**Comment by PureGero** [comment]
It appears your server is losing its connection to BungeeCord's MultiPaper-Master, are there any errors in the BungeeCord log?

**Comment by CivicXFB** [comment]
[latest.log](https://github.com/PureGero/MultiPaper/files/7315416/latest.log)
This is the bc-side log message

**Comment by CivicXFB** [comment]
okey
